
// This file is deprecated.
// The Service Worker is now automatically generated by vite-plugin-pwa at build time.
// We keep this file empty to ensure any manual registration in older versions is overwritten or ignored.
// Do not add manual caching logic here; use vite.config.ts for PWA configuration.
